[package]
name = "rust_ddd"
version = "0.1.0"
authors = ["Rbertko <myeongsku@mondrian.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
